import type { Metadata } from "next";

import "./globals.css";
import SideNavServer from "@/components/SideNav/SideNavServer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-auto flex-col md:flex-row md:overflow-hidden bg-gray-500/10">
          <div className="w-full flex-none md:w-64">
            <SideNavServer />
          </div>
          <div className="flex-grow p-4 text-gray-500">{children}</div>
        </div>
      </body>
    </html>
  );
}
